# Generated by Django 4.0.2 on 2022-02-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date_acquired', models.DateField()),
            ],
        ),
    ]
