# Generated by Django 4.0.2 on 2022-02-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Maintenance Date')),
                ('look_over', models.CharField(choices=[('B', 'Brushed'), ('W', 'Washed'), ('M', 'Mended')], default='B', max_length=1)),
                ('beanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.beanie')),
            ],
        ),
    ]
