# Generated by Django 4.0.2 on 2022-03-02 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='beanie',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='look_over',
            field=models.CharField(choices=[('B', 'Brushed'), ('W', 'Washed'), ('M', 'Mended')], default='B', max_length=1, verbose_name='To-Do-Item'),
        ),
    ]
